// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcaImporter.Infrastructure.Persistencia;

#nullable disable

namespace PcaImporter.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(PcaDbContext))]
    [Migration("20260508035601_AdicionarValorTotalHistorico")]
    partial class AdicionarValorTotalHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.HistoricoImportacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoDfd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdArtefato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdExecucao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("IdFormalizacaoDemanda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdPlanilha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroDfd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMateriais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("IdPlanilha");

                    b.ToTable("historico_importacoes", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.TokenSessaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tokens_sessao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
