// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcaImporter.Infrastructure.Persistencia;

#nullable disable

namespace PcaImporter.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(PcaDbContext))]
    [Migration("20260515190244_AdicionarClasseGrupoListaLink")]
    partial class AdicionarClasseGrupoListaLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.CatalogoMaterialEntity", b =>
                {
                    b.Property<int>("CodigoItem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AtualizadoEmFonte")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoClasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoGrupo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoNcm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoPdm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ItemSustentavel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeClasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeGrupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePdm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SincronizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusItem")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodigoItem");

                    b.HasIndex("CodigoClasse");

                    b.HasIndex("CodigoPdm");

                    b.ToTable("catalogo_materiais", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.HistoricoImportacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoDfd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<long>("IdArtefato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdExecucao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("IdFormalizacaoDemanda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdPlanilha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinhaErro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroDfd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMateriais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioLogin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("IdPlanilha");

                    b.ToTable("historico_importacoes", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DeltaPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("FingerprintVersao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Linha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("Tipo");

                    b.HasIndex("LinkId", "Fingerprint")
                        .IsUnique();

                    b.ToTable("lista_item", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemRevisaoEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevisadoPorLogin")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RevisadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "RevisadoPorLogin");

                    b.ToTable("lista_item_revisao", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPorLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcluidoPorLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdPlanilha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroGrupo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rotulo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalMateriais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExcluidoEm");

                    b.HasIndex("IdPlanilha")
                        .IsUnique()
                        .HasFilter("\"ExcluidoEm\" IS NULL");

                    b.HasIndex("Classe", "NumeroGrupo")
                        .IsUnique()
                        .HasFilter("\"ExcluidoEm\" IS NULL AND \"Classe\" IS NOT NULL AND \"NumeroGrupo\" IS NOT NULL");

                    b.ToTable("lista_link", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.TokenSessaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tokens_sessao", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPorLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Papel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemEntity", b =>
                {
                    b.HasOne("PcaImporter.Infrastructure.Persistencia.Entidades.ListaLinkEntity", "Link")
                        .WithMany("Itens")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemRevisaoEntity", b =>
                {
                    b.HasOne("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemEntity", "Item")
                        .WithMany("Revisoes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaItemEntity", b =>
                {
                    b.Navigation("Revisoes");
                });

            modelBuilder.Entity("PcaImporter.Infrastructure.Persistencia.Entidades.ListaLinkEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
